"""
KIP Enhanced Business Log Models — Sprint 6
Five-category log system with ML prediction support and market survey.
"""
from sqlalchemy import Column, Integer, String, DateTime, Text, Boolean, Float, ForeignKey, JSON
from datetime import datetime
from app.database import Base


class BusinessLogTemplate(Base):
    """
    Custom log template generated by KIP for a specific business type.
    Stores which custom fields/sub-fields to show for this business.
    Semi-adaptive: same 5 categories, custom sub-fields per business.
    """
    __tablename__ = "business_log_templates"
    id              = Column(Integer, primary_key=True, index=True)
    plan_id         = Column(Integer, ForeignKey("business_launch_plans.id"), nullable=False, unique=True)
    business_type   = Column(String(100), nullable=True)
    custom_fields   = Column(Text, nullable=False)  # JSON: {category: [field_names]}
    created_at      = Column(DateTime, default=datetime.utcnow)


class EnhancedDailyLog(Base):
    """
    Full 5-category daily business log.
    Replaces/extends the basic DailyBusinessLog.
    """
    __tablename__ = "enhanced_daily_logs"
    id              = Column(Integer, primary_key=True, index=True)
    plan_id         = Column(Integer, ForeignKey("business_launch_plans.id"), nullable=False)
    user_id         = Column(Integer, ForeignKey("users.id"), nullable=False)
    log_date        = Column(DateTime, default=datetime.utcnow)
    day_number      = Column(Integer, nullable=True)

    # ── Category 1: Financial ──────────────────────────────────────────────
    total_revenue       = Column(Float, default=0.0)      # Total sales ZMW
    cash_received       = Column(Float, default=0.0)      # Actual cash in
    mobile_money_received = Column(Float, default=0.0)    # MoMo / Airtel Money
    total_expenses      = Column(Float, default=0.0)      # All outflows
    expense_breakdown   = Column(Text, nullable=True)     # JSON: {category: amount}
    daily_profit        = Column(Float, default=0.0)      # Revenue - Expenses
    # Custom revenue streams per business (e.g. "Screen repairs: K450")
    revenue_by_product  = Column(Text, nullable=True)     # JSON: {product: amount}

    # ── Category 2: Customers & Sales ─────────────────────────────────────
    total_customers     = Column(Integer, default=0)
    new_customers       = Column(Integer, default=0)
    repeat_customers    = Column(Integer, default=0)
    walk_ins            = Column(Integer, default=0)      # People who entered/enquired
    conversions         = Column(Integer, default=0)      # People who actually bought
    avg_sale_value      = Column(Float, default=0.0)      # Auto-calculated
    refunds_count       = Column(Integer, default=0)
    refunds_amount      = Column(Float, default=0.0)
    customer_note       = Column(String(500), nullable=True)  # Key comment/complaint

    # ── Category 3: Operations & Inventory ────────────────────────────────
    hours_open          = Column(Float, default=0.0)
    units_produced      = Column(Integer, default=0)      # If manufacturing
    orders_fulfilled    = Column(Integer, default=0)      # If delivery/service
    stock_status        = Column(String(20), default="sufficient")  # sufficient|low|critical
    stock_movements     = Column(Text, nullable=True)     # JSON: {item: {in, out, waste}}
    downtime_minutes    = Column(Integer, default=0)
    downtime_reason     = Column(String(300), nullable=True)
    # Custom operational metric (e.g. "Devices repaired: 12" for repair shop)
    custom_metric_name  = Column(String(100), nullable=True)
    custom_metric_value = Column(Float, default=0.0)

    # ── Category 4: Marketing & Leads ─────────────────────────────────────
    marketing_actions   = Column(Text, nullable=True)     # What was done today
    marketing_spend     = Column(Float, default=0.0)      # ZMW spent on marketing
    leads_generated     = Column(Integer, default=0)
    best_channel        = Column(String(100), nullable=True)  # WhatsApp / Facebook / Referral

    # ── Category 5: Time & Productivity ───────────────────────────────────
    hours_worked        = Column(Float, default=0.0)
    time_breakdown      = Column(Text, nullable=True)     # JSON: {activity: hours}
    daily_win           = Column(String(500), nullable=True)   # What went well
    daily_lesson        = Column(String(500), nullable=True)   # What slowed you down

    # ── KIP Coaching ──────────────────────────────────────────────────────
    coaching_response   = Column(Text, nullable=True)
    coaching_at         = Column(DateTime, nullable=True)

    created_at          = Column(DateTime, default=datetime.utcnow)


class WeeklyReview(Base):
    """
    Auto-generated weekly KPI summary with ML-derived insights.
    Generated every Monday or on demand.
    """
    __tablename__ = "weekly_reviews"
    id              = Column(Integer, primary_key=True, index=True)
    plan_id         = Column(Integer, ForeignKey("business_launch_plans.id"), nullable=False)
    user_id         = Column(Integer, ForeignKey("users.id"), nullable=False)
    week_start      = Column(DateTime, nullable=False)
    week_end        = Column(DateTime, nullable=False)

    # KPI snapshots
    total_revenue       = Column(Float, default=0.0)
    total_expenses      = Column(Float, default=0.0)
    net_profit          = Column(Float, default=0.0)
    avg_daily_customers = Column(Float, default=0.0)
    avg_sale_value      = Column(Float, default=0.0)
    total_logs_filed    = Column(Integer, default=0)

    # vs previous week
    revenue_change_pct  = Column(Float, nullable=True)
    customer_change_pct = Column(Float, nullable=True)

    # ML outputs
    top_selling_product = Column(String(200), nullable=True)
    biggest_expense_cat = Column(String(100), nullable=True)
    peak_day            = Column(String(20), nullable=True)      # e.g. "Friday"
    trend_status        = Column(String(20), default="neutral")  # green|yellow|red

    # KIP narrative summary
    kip_summary         = Column(Text, nullable=True)
    predictions_json    = Column(Text, nullable=True)  # JSON: ML prediction outputs

    created_at          = Column(DateTime, default=datetime.utcnow)


class MLPrediction(Base):
    """
    Stores rolling ML predictions generated from log data.
    Updated each time a new log is submitted.
    """
    __tablename__ = "ml_predictions"
    id              = Column(Integer, primary_key=True, index=True)
    plan_id         = Column(Integer, ForeignKey("business_launch_plans.id"), nullable=False)
    user_id         = Column(Integer, ForeignKey("users.id"), nullable=False)
    generated_at    = Column(DateTime, default=datetime.utcnow)

    # Revenue forecast (next 7 days)
    revenue_forecast_7d = Column(Text, nullable=True)  # JSON: [day1, day2, ..., day7]
    forecast_confidence = Column(Float, nullable=True)  # 0-1

    # Customer trend
    customer_trend      = Column(String(20), nullable=True)  # rising|stable|falling
    customer_trend_pct  = Column(Float, nullable=True)

    # Peak detection
    peak_day_of_week    = Column(String(20), nullable=True)
    peak_hour_range     = Column(String(50), nullable=True)

    # Stock depletion
    days_until_stockout = Column(Integer, nullable=True)
    low_stock_items     = Column(Text, nullable=True)   # JSON list

    # Expense anomaly
    expense_anomaly     = Column(Boolean, default=False)
    anomaly_category    = Column(String(100), nullable=True)
    anomaly_detail      = Column(String(300), nullable=True)

    # Break-even progress
    breakeven_progress_pct = Column(Float, nullable=True)
    days_to_breakeven      = Column(Integer, nullable=True)


class MarketSurvey(Base):
    """
    Market knowledge survey completed by the user about their business location.
    Feeds into KIP's contextual intelligence layer.
    """
    __tablename__ = "market_surveys"
    id              = Column(Integer, primary_key=True, index=True)
    user_id         = Column(Integer, ForeignKey("users.id"), nullable=False)
    plan_id         = Column(Integer, ForeignKey("business_launch_plans.id"), nullable=True)
    location        = Column(String(255), nullable=True)
    completed_at    = Column(DateTime, nullable=True)

    # Section 1: Location & Infrastructure
    area_type           = Column(String(30), nullable=True)   # residential/commercial/market/cbd
    foot_traffic        = Column(String(20), nullable=True)   # very_high/high/medium/low
    road_access         = Column(String(20), nullable=True)   # tarmac/gravel/poor
    power_reliability   = Column(String(20), nullable=True)   # reliable/load_shedding/unreliable
    internet_access     = Column(String(20), nullable=True)   # good/fair/poor/none
    has_nearby_market   = Column(Boolean, default=False)
    market_distance_km  = Column(Float, nullable=True)

    # Section 2: Customer Profile
    dominant_income_level = Column(String(20), nullable=True)  # low/lower_mid/middle/upper
    primary_occupation    = Column(String(100), nullable=True)  # mining/farming/govt/trade/etc
    peak_shopping_time    = Column(String(50), nullable=True)   # morning/afternoon/evening/weekend
    payment_preference    = Column(String(50), nullable=True)   # cash/mobile_money/mix
    avg_spend_per_visit   = Column(Float, nullable=True)        # ZMW estimate

    # Section 3: Competition
    direct_competitors_count  = Column(Integer, nullable=True)
    competition_quality       = Column(String(20), nullable=True)  # strong/moderate/weak/none
    main_competitor_weakness  = Column(String(300), nullable=True)
    market_gaps_noted         = Column(Text, nullable=True)  # what's missing in the area

    # Section 4: Supply Chain
    nearest_wholesale_km  = Column(Float, nullable=True)
    supplier_reliability  = Column(String(20), nullable=True)  # good/fair/poor
    main_supply_source    = Column(String(200), nullable=True)  # e.g. Chisokone Market

    # Section 5: Business Environment
    has_cdf_office      = Column(Boolean, default=False)
    has_ceec_office     = Column(Boolean, default=False)
    has_bank_branch     = Column(Boolean, default=False)
    security_level      = Column(String(20), nullable=True)  # safe/moderate/risky
    seasonal_business   = Column(Boolean, default=False)
    peak_season_months  = Column(String(100), nullable=True)  # e.g. "December-January"

    # Free-form observations
    additional_notes    = Column(Text, nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
